# Semgrep Scanner Action
#
# This composite action executes static analysis security testing using Semgrep,
# providing comprehensive code analysis capabilities.
#
# Key Features:
# - Multi-language support
# - Custom rule sets
# - Incremental scanning
# - SARIF reporting
# - Performance optimization
#
# Process Stages:
# 1. Environment Setup:
#    - Python installation
#    - Semgrep configuration
#    - Rule preparation
#
# 2. Scan Execution:
#    - Target selection
#    - Rule application
#    - Code analysis
#
# 3. Results Processing:
#    - Report generation
#    - Finding analysis
#    - Output formatting
#
# Required Inputs:
# - scan-scope: Files to scan
# - config: Rule configuration
# - severity: Issue threshold
#
# Outputs:
# - scan_result: Scan exit code
# - report_path: Results location
#
# Example Usage:
# steps:
#   - uses: ./actions/semgrep
#     with:
#       scan-scope: "changed"
#       config: "p/owasp-top-ten"
#
# Note: Consider using custom rule sets for project-specific checks

name: "Semgrep SAST Scan"
description: "Runs Semgrep security scanner with configurable options"

inputs:
  scan-scope:
    description: "Scope of files to scan (all/changed)"
    required: false
    default: "changed"
  paths:
    description: "Paths to scan when using all scope"
    required: false
    default: "."
  config:
    description: "Semgrep rules or config to use"
    required: false
    default: "p/default p/cwe-top-25 p/trailofbits p/owasp-top-ten"
  severity:
    description: "Minimum severity level to report (LOW/MEDIUM/HIGH/CRITICAL)"
    required: false
    default: "LOW"
  timeout:
    description: "Maximum time to run semgrep in seconds"
    required: false
    default: "300"
  output-format:
    description: "Format for scan results (text/json/sarif)"
    required: false
    default: "sarif"
  fail-on-findings:
    description: "Whether to fail the action if issues are found"
    required: false
    default: "true"
  semgrep-version:
    description: "Semgrep version"
    required: false
    # renovate: datasource=pypi depName=semgrep
    default: 1.132.0

outputs:
  scan_result:
    description: "Exit code of the Semgrep scan"
    value: ${{ steps.run-semgrep.outputs.exit_code }}
  report_path:
    description: "Path to the generated report file"
    value: ${{ steps.run-semgrep.outputs.report_path }}

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: "3.10"

    - name: Install Semgrep
      shell: bash
      env:
        SEMGREP_VERSION: ${{ inputs.semgrep-version }}
      run: |
        python -m pip install --upgrade pip
        pip install semgrep=="$SEMGREP_VERSION"

    - name: Run Semgrep scan
      id: run-semgrep
      shell: bash
      # Set the SEMGREP_RULES environment variable to specify which rules Semgrep should use.
      env:
        SEMGREP_RULES: ${{ inputs.config }}
        INPUTS_SCAN_SCOPE: ${{ inputs.scan-scope }}
        INPUTS_PATHS: ${{ inputs.paths }}
        INPUTS_SEVERITY: ${{ inputs.severity }}
        INPUTS_TIMEOUT: ${{ inputs.timeout }}
        INPUTS_OUTPUT_FORMAT: ${{ inputs.output-format }}
      run: |
        set +e
        # Map standard severity levels to Semgrep's levels
        # Semgrep does not support hierarchy, levels must be set explicitly
        case "$INPUTS_SEVERITY" in
          "LOW")
            SEMGREP_SEVERITY="--severity INFO --severity WARNING --severity ERROR"
            ;;
          "MEDIUM")
            SEMGREP_SEVERITY="--severity WARNING --severity ERROR"
            ;;
          "HIGH"|"CRITICAL")
            SEMGREP_SEVERITY="--severity ERROR"
            ;;
          *)
            SEMGREP_SEVERITY="--severity WARNING --severity ERROR"
            ;;
        esac

        # Create results directory
        mkdir -p security-results/semgrep

        REPORT_FILE="security-results/semgrep/semgrep-results.$INPUTS_OUTPUT_FORMAT"
        SARIF_FILE="security-results/semgrep/semgrep-results.sarif"

        if [[ "$INPUTS_SCAN_SCOPE" == "changed" ]]; then
          echo "Running Semgrep on changed scope - diff-aware scan:"
          echo "baseline-commit is ${{ github.event.pull_request.base.sha }}"

          # On changed scope (i.e., check on PR), we output results in a text format into console
          # and duplicate it into SARIF file with --sarif-output
          # SARIF results will be uploaded into PR comments for public repos
          # baseline-commit is used to trigger diff-aware scan
          semgrep scan \
            ${SEMGREP_SEVERITY} \
            --error \
            --text \
            --sarif-output="${SARIF_FILE}" \
            --timeout "$INPUTS_TIMEOUT" \
            --metrics=off \
            --baseline-commit ${{ github.event.pull_request.base.sha }} \

          exit_code="$?"
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
          echo "report_path=${REPORT_FILE}" >> $GITHUB_OUTPUT

        elif [[ "$INPUTS_SCAN_SCOPE" == "all" ]] ; then
          echo "Running Semgrep on all files in $INPUTS_PATHS"
          # Scan and output resulsts into workflow log and SARIF
          # SARIF results will be uploaded into Security tab for public repos
          semgrep scan \
            ${SEMGREP_SEVERITY} \
            --error \
            --text \
            --sarif-output="${SARIF_FILE}" \
            --timeout "$INPUTS_TIMEOUT" \
            --metrics=off \
            "$INPUTS_PATHS"

         if [[ "$INPUTS_OUTPUT_FORMAT" != "sarif" ]]; then
          # Second scan to get output file in text or json format
          # Shall not take too much time due to Semgrep caching
            semgrep scan \
              ${SEMGREP_SEVERITY} \
              --error \
              --timeout "$INPUTS_TIMEOUT" \
              --"$INPUTS_OUTPUT_FORMAT" \
              -o "${REPORT_FILE}" \
              --metrics=off \
              "$INPUTS_PATHS"
            exit_code="$?"
            echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
            echo "report_path=${REPORT_FILE}" >> $GITHUB_OUTPUT
          fi

        else
          echo "No files to scan found"
        fi

    - name: Upload reports
      if: hashFiles('security-results/semgrep/*') != '' # if any report is available
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: semgrep-results
        path: security-results/semgrep
        retention-days: 7

    - name: Upload reports in SARIF
      # Upload report if SARIF file is available and repo is public
      if: github.event.repository.private == false && hashFiles('security-results/semgrep/semgrep-results.sarif') != ''
      uses: github/codeql-action/upload-sarif@51f77329afa6477de8c49fc9c7046c15b9a4e79d # v3.29.5
      with:
        sarif_file: security-results/semgrep/semgrep-results.sarif

    - name: Complete with exit code
      shell: bash
      env:
        INPUTS_FAIL_ON_FINDINGS: ${{ inputs.fail-on-findings }}
        EXIT_CODE: ${{ steps.run-semgrep.outputs.exit_code}}
      run: |
        set +e
        if [[ "$INPUTS_FAIL_ON_FINDINGS" == "true" && -n "$EXIT_CODE" && "$EXIT_CODE" != "0" ]]; then
          exit $EXIT_CODE
        fi
