# Semgrep Scanner Action
#
# This composite action executes static analysis security testing using Semgrep,
# providing comprehensive code analysis capabilities.
#
# Key Features:
# - Multi-language support
# - Custom rule sets
# - Incremental scanning
# - SARIF reporting
# - Performance optimization
#
# Process Stages:
# 1. Environment Setup:
#    - Python installation
#    - Semgrep configuration
#    - Rule preparation
#
# 2. Scan Execution:
#    - Target selection
#    - Rule application
#    - Code analysis
#
# 3. Results Processing:
#    - Report generation
#    - Finding analysis
#    - Output formatting
#
# Required Inputs:
# - scan-scope: Files to scan
# - config: Rule configuration
# - severity: Issue threshold
#
# Outputs:
# - scan_result: Scan exit code
# - report_path: Results location
#
# Note: Consider using custom rule sets for project-specific checks

name: "Semgrep SAST Scan"
description: "Runs Semgrep security scanner with configurable options"

inputs:
  scan-scope:
    description: "Scope of files to scan (all/changed)"
    required: false
    default: "changed"
  paths:
    description: "Paths to scan when using all scope"
    required: false
    default: "."
  config:
    description: "Semgrep rules or config to use"
    required: false
    default: "p/default p/cwe-top-25 p/trailofbits p/owasp-top-ten"
  severity:
    description: "Minimum severity level to report (LOW/MEDIUM/HIGH/CRITICAL)"
    required: false
    default: "LOW"
  timeout:
    description: "Maximum time to run semgrep in seconds"
    required: false
    default: "300"
  output-format:
    description: "Format for scan results (text/json/sarif)"
    required: false
    default: "sarif"
  fail-on-findings:
    description: "Whether to fail the action if issues are found"
    required: false
    default: "true"
  semgrep-version:
    description: "Semgrep version"
    required: false
    # renovate: datasource=pypi depName=semgrep
    default: 1.143.1

outputs:
  scan_result:
    description: "Exit code of the Semgrep scan"
    value: ${{ steps.run-semgrep.outputs.exit_code }}
  report_path:
    description: "Path to the generated report file"
    value: ${{ steps.run-semgrep.outputs.report_path }}

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: "3.10"

    - name: Install Semgrep
      shell: bash
      env:
        SEMGREP_VERSION: ${{ inputs.semgrep-version }}
      run: |
        python -m pip install --upgrade pip
        pip install semgrep=="$SEMGREP_VERSION"

    - name: Run Semgrep scan
      id: run-semgrep
      shell: bash
      env:
        # https://semgrep.dev/docs/semgrep-ci/ci-environment-variables#semgrep_rules
        SEMGREP_RULES: ${{ inputs.config }}
        INPUTS_SCAN_SCOPE: ${{ inputs.scan-scope }}
        INPUTS_PATHS: ${{ inputs.paths }}
        INPUTS_SEVERITY: ${{ inputs.severity }}
        INPUTS_TIMEOUT: ${{ inputs.timeout }}
        INPUTS_OUTPUT_FORMAT: ${{ inputs.output-format }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
      run: |
        set +e
        # Map standard severity levels to Semgrep's levels
        # Semgrep does not support hierarchy, levels must be set explicitly
        case "$INPUTS_SEVERITY" in
          "LOW")
            SEMGREP_SEVERITY="--severity INFO --severity WARNING --severity ERROR"
            ;;
          "MEDIUM")
            SEMGREP_SEVERITY="--severity WARNING --severity ERROR"
            ;;
          "HIGH"|"CRITICAL")
            SEMGREP_SEVERITY="--severity ERROR"
            ;;
          *)
            SEMGREP_SEVERITY="--severity WARNING --severity ERROR"
            ;;
        esac

        # Create results directory
        mkdir -p security-results/semgrep

        SARIF_FILE="security-results/semgrep/semgrep-results.sarif"

        if [[ "$INPUTS_SCAN_SCOPE" == "changed" ]]; then
          echo "Running Semgrep on changed scope with diff-aware scan:"
          echo "baseline-commit is ${BASE_SHA}"

          # On changed scope (i.e., check on PR), action outputs results in a text format into console
          # and duplicates it into SARIF file with --sarif-output
          # SARIF results will be uploaded into PR comments for public repos
          # baseline-commit is used to trigger diff-aware scan
          semgrep scan \
            ${SEMGREP_SEVERITY} \
            --error \
            --text \
            --sarif-output="${SARIF_FILE}" \
            --timeout "$INPUTS_TIMEOUT" \
            --metrics=off \
            --baseline-commit "${BASE_SHA}" \

          exit_code="$?"
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
          echo "report_path=${SARIF_FILE}" >> $GITHUB_OUTPUT

        elif [[ "$INPUTS_SCAN_SCOPE" == "all" ]] ; then
          echo "Running Semgrep on all files in $INPUTS_PATHS"

          # Scan full scope and output results into workflow log and SARIF file
          # For public repos SARIF results will be uploaded into Security tab
          semgrep scan \
            ${SEMGREP_SEVERITY} \
            --error \
            --text \
            --sarif-output="${SARIF_FILE}" \
            --timeout "$INPUTS_TIMEOUT" \
            --metrics=off \
            "$INPUTS_PATHS"
          exit_code="$?"
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
          echo "report_path=${SARIF_FILE}" >> $GITHUB_OUTPUT

          # Second scan to get output file in text or json format,
          # if it is required by provided output-format (Semgrep can not do it in one go)
          # Shall not take too much time due to Semgrep caching

          if [[ "$INPUTS_OUTPUT_FORMAT" != "sarif" ]]; then
              REPORT_FILE="security-results/semgrep/semgrep-results.$INPUTS_OUTPUT_FORMAT"
              semgrep scan \
                ${SEMGREP_SEVERITY} \
                --error \
                --timeout "$INPUTS_TIMEOUT" \
                --"$INPUTS_OUTPUT_FORMAT" \
                -o "${REPORT_FILE}" \
                --metrics=off \
                "$INPUTS_PATHS"
              exit_code="$?"
              echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
              echo "report_path=${REPORT_FILE}" >> $GITHUB_OUTPUT
            fi

        else
          echo "No files to scan found"
        fi

    - name: Upload reports
      if: hashFiles('security-results/semgrep/*') != '' # if any report is available
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
      with:
        name: semgrep-results
        path: security-results/semgrep
        retention-days: 7

    - name: Upload reports in SARIF
      # Upload report if SARIF file is available and repo is public
      if: github.event.repository.private == false && hashFiles('security-results/semgrep/semgrep-results.sarif') != ''
      uses: github/codeql-action/upload-sarif@fdbfb4d2750291e159f0156def62b853c2798ca2 # v4.31.5
      with:
        sarif_file: security-results/semgrep/semgrep-results.sarif

    - name: Complete with exit code
      shell: bash
      env:
        INPUTS_FAIL_ON_FINDINGS: ${{ inputs.fail-on-findings }}
        EXIT_CODE: ${{ steps.run-semgrep.outputs.exit_code}}

      run: |
        # Respect INPUTS_FAIL_ON_FINDINGS only if exit code == 1
        # Otherwise, use exit code to catch Semgrep internal issues
        # https://semgrep.dev/docs/cli-reference#exit-codes

        set +e
        if [[ "$INPUTS_FAIL_ON_FINDINGS" == "false" && -n "$EXIT_CODE" && "$EXIT_CODE" == "1" ]]; then
          exit 0
        else
          exit $EXIT_CODE
        fi
