# Bandit Scanner Action
#
# This composite action executes Python security scanning using Bandit,
# providing configurable security analysis capabilities.

name: "Bandit Security Scan"
description: "Runs Bandit security scanner with configurable options"

inputs:
  scan-scope:
    description: "Scope of files to scan (all/changed)"
    required: false
    default: "changed"
  paths:
    description: "Paths to scan when using all scope"
    required: false
    default: "." # all scope by default, exclude_dirs are taken from pyproject.toml
  config_file:
    description: "Path to pyproject.toml or custom bandit config"
    required: false
    default: "pyproject.toml"
  severity-level:
    description: "Minimum severity level to report (LOW/MEDIUM/HIGH/CRITICAL)"
    required: false
    default: "LOW"
  confidence-level:
    description: "Minimum confidence level to report (LOW/MEDIUM/HIGH)"
    required: false
    default: "LOW"
  output-format:
    description: "Format for scan results (json/txt/html/csv/sarif)"
    required: false
    default: "txt"
  fail-on-findings:
    description: "Whether to fail the action if issues are found"
    required: false
    default: "true"
  upload-sarif:
    description: "Whether to upload SARIF results"
    required: false
    default: "true"
  bandit-version:
    description: "bandit version"
    required: false
    # renovate: datasource=pypi depName=bandit
    default: 1.9.2

outputs:
  scan_result:
    description: "Exit code of the Bandit scan"
    value: ${{ steps.run-bandit.outputs.exit_code }}
  report_path:
    description: "Path to the generated report file"
    value: ${{ steps.run-bandit.outputs.report_path }}

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: "3.10"

    - name: Install Bandit
      shell: bash
      env:
        BANDIT_VERSION: ${{ inputs.bandit-version }}
      run: |
        python -m pip install --upgrade pip
        pip install bandit[toml,sarif]=="$BANDIT_VERSION"

    - name: Get changed files
      if: inputs.scan-scope == 'changed'
      id: changed-files
      uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # v47.0.1
      with:
        files: |
          **/*.py
          **/*.pyx
          **/*.pyi

    - name: Run Bandit scan
      id: run-bandit
      shell: bash
      env:
        INPUTS_SCAN_SCOPE: ${{ inputs.scan-scope }}
        INPUTS_PATHS: ${{ inputs.paths }}
        INPUTS_CONFIG_FILE: ${{ inputs.config_file }}
        INPUTS_SEVERITY_LEVEL: ${{ inputs.severity-level }}
        INPUTS_CONFIDENCE_LEVEL: ${{ inputs.confidence-level }}
        INPUTS_OUTPUT_FORMAT: ${{ inputs.output-format }}
        INPUTS_FAIL_ON_FINDINGS: ${{ inputs.fail-on-findings }}
        INPUTS_ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        set +e
        REPORT_FILE="bandit-report.$INPUTS_OUTPUT_FORMAT"
        SARIF_FILE="bandit-report.sarif"

        # Convert confidence to lowercase
        CONFIDENCE=$(echo "$INPUTS_CONFIDENCE_LEVEL" | tr '[:upper:]' '[:lower:]')

        # Map standard severity levels to Bandit levels
        # Bandit uses: low, medium, high
        # Standard levels: LOW, MEDIUM, HIGH, CRITICAL
        case "$INPUTS_SEVERITY_LEVEL" in
          "LOW")
            SEVERITY="low"
            ;;
          "MEDIUM")
            SEVERITY="medium"
            ;;
          "HIGH"|"CRITICAL")
            SEVERITY="high"
            ;;
          *)
            SEVERITY="high"
            ;;
        esac

        # Check if config file is provided
        if [[ -f "$INPUTS_CONFIG_FILE" ]]; then
          CONFIG_OPTION="-c $INPUTS_CONFIG_FILE"
        else
          CONFIG_OPTION=""
        fi

        if [[ "$INPUTS_SCAN_SCOPE" == "changed" && -n "${INPUTS_ALL_CHANGED_FILES}" ]]; then
          echo "There are some changes detected, running Bandit"
          echo "Changed files: ${INPUTS_ALL_CHANGED_FILES}"
          FILES="${INPUTS_ALL_CHANGED_FILES}"

          # First run is to produce output in SARIF format
           bandit \
            -a file \
            ${CONFIG_OPTION} \
            --exit-zero \
            --severity-level ${SEVERITY} \
            --confidence-level ${CONFIDENCE} \
            -f sarif \
            -o "${SARIF_FILE}" \
            -r ${FILES}

          # Second run is to produce plain report and output into workflow log
          # This is necessary for private repos that may not have Advanced Security subscription
          # And therefore, SARIF upload can not be used
          bandit \
            -a file \
            ${CONFIG_OPTION} \
            --severity-level ${SEVERITY} \
            --confidence-level ${CONFIDENCE} \
            -r ${FILES}
          exit_code="$?"
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT

        elif [[ "$INPUTS_SCAN_SCOPE" == "all" ]] ; then
          echo "Running Bandit on all files in $INPUTS_PATHS"
          # First run to produce SARIF for upload into Security tab
          bandit \
            ${CONFIG_OPTION} \
            --severity-level ${SEVERITY} \
            --confidence-level ${CONFIDENCE} \
            --exit-zero \
            -f sarif \
            -o "${SARIF_FILE}" \
            -r "$INPUTS_PATHS"

          # Second run to produce txt/csv/etc report
          # This is required for private repos that may not have Advanced Security subscription
          bandit \
            ${CONFIG_OPTION} \
            --severity-level ${SEVERITY} \
            --confidence-level ${CONFIDENCE} \
            -f "$INPUTS_OUTPUT_FORMAT" \
            -o "${REPORT_FILE}" \
            -r "$INPUTS_PATHS"
          exit_code="$?"
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
          echo "report_path=${REPORT_FILE}" >> $GITHUB_OUTPUT
        else
          echo "No files to scan found"
        fi

    # GitHub supports an additional security-severity property in SARIF.
    # This step enriches original Bandit SARIF report with this security-severity property based on alert levels as per GitHub's SARIF specification.
    # This is necessary for unification across used security tools that produce and upload SARIF output.
    # Numeric values are used to make the following addition based on level:
    # - error -> high (8.0)
    # - warning -> medium (5.0)
    # - note -> low (3.0)
    # - none -> none (0.0)
    - name: Add SARIF security-severity to properties
      if: hashFiles('bandit-report.sarif') != ''
      shell: bash
      run: |
        jq '
          .runs[0].results |= map(
            .properties["security-severity"] = (
              if .level == "error" then "8.0"
              elif .level == "warning" then "5.0"
              elif .level == "note" then "3.0"
              elif .level == "none" then "0.0"
              else null
              end
            )
          )
        ' bandit-report.sarif > updated-report.sarif
        mv updated-report.sarif bandit-report.sarif

      # Upload results after full scope analysis
    - name: Upload reports
      if: hashFiles('bandit-report.*') != '' # if any report is available
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: bandit-results
        path: bandit-report.*
        retention-days: 7

    - name: Upload SARIF
      # If SARIF is available, upload it considering that for private repos Advanced Security subscription is n/a
      # but will be visible in workflow log
      if: inputs.upload-sarif == 'true' && github.event.repository.private == false && hashFiles('bandit-report.sarif') != ''
      uses: github/codeql-action/upload-sarif@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4.31.9
      with:
        sarif_file: bandit-report.sarif
        category: bandit

    - name: Complete with exit code
      shell: bash
      env:
        INPUTS_FAIL_ON_FINDINGS: ${{ inputs.fail-on-findings }}
        EXIT_CODE: ${{ steps.run-bandit.outputs.exit_code}}

      run: |
        # Respect INPUTS_FAIL_ON_FINDINGS setting
        # Exit with the scan's exit code if fail-on-findings is true and findings exist

        set +e
        if [[ "$INPUTS_FAIL_ON_FINDINGS" == "false" && -n "$EXIT_CODE" && "$EXIT_CODE" != "0" ]]; then
          echo "Findings detected but fail-on-findings is false, exiting with success"
          exit 0
        elif [[ -n "$EXIT_CODE" ]]; then
          exit "$EXIT_CODE"
        else
          echo "No exit code set, assuming success"
          exit 0
        fi
