name: Collect Library Licenses
description: "Collects license information for the library dependencies and uploads as a CSV artifact."

inputs:
  path:
    description: "Path to the pyproject.toml file"
    required: true
  extras:
    description: "Comma-separated list of extras to install (e.g., 'full' or 'dev,test'). Leave empty for no extras."
    required: true
  artifact-name:
    description: "Name of the uploaded artifact"
    required: false
    default: "licenses-list-csv"
  uv-version:
    description: "Version of uv to install"
    required: false
    default: "0.9.7"

runs:
  using: "composite"
  steps:
    - name: Validate extras input
      shell: bash
      env:
        EXTRAS: ${{ inputs.extras }}
      run: |
        if [ -n "$EXTRAS" ]; then
          # Validate that extras only contain valid characters (alphanumeric, underscores, hyphens, commas)
          # This prevents injection of malicious flags like --index-url
          if ! echo "$EXTRAS" | grep -qE '^[a-zA-Z0-9_,-]+$'; then
            echo "::error::Invalid extras input. Extras must only contain alphanumeric characters, underscores, hyphens, and commas."
            echo "::error::Received: $EXTRAS"
            exit 1
          fi
          # Additional check: ensure no extra starts with a dash (flag injection attempt)
          for extra in $(echo "$EXTRAS" | tr ',' ' '); do
            if [[ "$extra" == -* ]]; then
              echo "::error::Invalid extra '$extra'. Extras cannot start with a dash."
              exit 1
            fi
          done
          echo "Extras validation passed: $EXTRAS"
        fi

    - name: Install uv
      uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
      with:
        version: ${{ inputs.uv-version }}

    - name: Collect licenses
      shell: bash
      working-directory: ${{ inputs.path }}
      env:
        EXTRAS: ${{ inputs.extras }}
      run: |
        if [ -n "$EXTRAS" ]; then
          # Convert comma-separated extras to --extra flags
          EXTRA_FLAGS=$(echo "$EXTRAS" | tr ',' '\n' | sed 's/^/--extra /' | tr '\n' ' ')
          uv sync --frozen $EXTRA_FLAGS
        else
          uv sync --frozen
        fi
        uv pip install 'pip-licenses==5.5.0'
        uv run pip-licenses
        uv run pip-licenses --format=csv --output-file=licenses-library.csv

    - name: Upload CSV
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.path }}/licenses-library.csv
        retention-days: 30
