# This workflow implements quality checks

name: Pre-merge checks

on:
  pull_request:
    branches:
      - main
    types:
      - edited
      - opened
      - ready_for_review
      - synchronize

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run pre-commit check
        uses: ./actions/pre-commit
