# Renovate configuration validator
#
# This workflow validates changes proposed into Renovate configuration file,
# located .github/renovate.json5.
#
# Key Features:
# - Validate changes and prevent non-valid configuration to be used by Renovate.
#
# Process Stages:
# Configuration validation:
#    - Runs on PR into .github/renovate.json5 and validate changes.
#
# Required Secrets:
# - None
#
# Example Usage:
# Automatically triggered on:
# - Pull requests to .github/renovate.json5.
#
# Note: None.

name: Validate Renovate configuration

on:
  pull_request:
    paths:
      - ".github/renovate.json5"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout configuration
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Validate configuration
        run: |
          # renovate: datasource=docker
          export RENOVATE_IMAGE=ghcr.io/renovatebot/renovate:40.11
          docker run --rm --entrypoint "renovate-config-validator" \
          -v "${{ github.workspace }}/.github/renovate.json5":"/renovate.json5" \
          ${RENOVATE_IMAGE} "/renovate.json5"
